### ISSUE TITLE
xcode project file integration

### ISSUE THREAD

**Issue by kodydeda4** [wojciech-kulik/xcodebuild.nvim#146]
Hey! 
I love the plugin, but i'm experiencing issues trying to create, edit or remove files.
I started with [ios-dev-starter-nvim](https://github.com/wojciech-kulik/ios-dev-starter-nvim)

Here's the error:
```
Could not update Xcode project file.
To see more details please check /tmp/xcodebuild_nvimtree.
If you are trying to add files to SPM packages, you may want to filter them out in the config using: integrations.nvim_tree.should_update_project.
If the error is unexpected, please open an issue on GitHub.
```
/tmp/xcodebuild_nvimtree output:
```
/Users/kodydeda/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:40:in `find_group_by_absolute_dir_path': undefined method `filter_map' for #<Enumerator::Lazy:0x000000013c5cec38> (NoMethodError)
Did you mean?  filter
	from /Users/kodydeda/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:209:in `find_targets_for_group'
	from /Users/kodydeda/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:262:in `add_file'
	from /Users/kodydeda/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:287:in `handle_action'
	from /Users/kodydeda/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:348:in `<main>'
```

**Comment by wojciech-kulik** [comment]
Hello,

You've got outdated ruby version :). 

You can additionally run `:checkhealth xcodebuild` to see if there are also any other issues.

**Comment by kodydeda4** [comment]
Absolute king. Thank you sir
