### ISSUE TITLE
Crash when adding/renaming a file

### ISSUE THREAD

**Issue by ychie** [wojciech-kulik/xcodebuild.nvim#161]
I experience constant crashes when trying to add/rename a file using nvim-tree. Can anyone help?

`
/Users/ychie/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:40:in `find_group_by_absolute_dir_path': undefined method `filter_map' for #<Enumerator::Lazy:0x000000012499ccb0> (NoMethodError)
Did you mean?  filter
	from /Users/ychie/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:209:in `find_targets_for_group'
	from /Users/ychie/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:262:in `add_file'
	from /Users/ychie/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:287:in `handle_action'
	from /Users/ychie/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:348:in `<main>'
`

**Comment by wojciech-kulik** [comment]
For others: It’s caused by an outdated ruby version :). Run „:checkhealth xcodebuild” to see if everything is ok with your environment
