### ISSUE TITLE
error on adding new file from NvimTree

### ISSUE THREAD

**Issue by humblehacker** [wojciech-kulik/xcodebuild.nvim#83]
I tried to add a new file and got an error after selecting the target. The error pointed me to `/tmp/xcodebuild_nvimtree` where I found this error: 
```
~/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:28:in `find_group_by_absolute_dir_path': undefined method `filter_map' for #<Enumerator::Lazy:0x0000000101058730> (NoMethodError)
  Did you mean?  filter
          from /Users/david/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:102:in `block in add_group'
          from /Users/david/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:99:in `each'
          from /Users/david/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:99:in `add_group'
          from /Users/david/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:185:in `handle_action'
          from /Users/david/.local/share/nvim/lazy/xcodebuild.nvim/tools/project_helper.rb:219:in `<main>'
```

**Comment by wojciech-kulik** [comment]
Hi! You are using an old Ruby version. `filter_map` was introduced in Ruby 2.7. Please update it, should help :)

**Comment by humblehacker** [comment]
ah, yeah. I should have noticed that. I recently wiped out my ruby install since I wasn't using it, leaving the very old macOS default.
